version: "3.9"

services:
  db:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=lngwediprlrdlw
      - POSTGRES_PASSWORD=CgN2PHwaYmh@oO0K3BBK
      - POSTGRES_DB=postgres

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - "9001:9001"
    volumes:
      - minio:/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: uvicorn run:app --host 0.0.0.0 --port 8000 --root-path /api
    environment:
      - POSTGRES_LOGIN=lngwediprlrdlw
      - POSTGRES_PASSWORD=CgN2PHwaYmh@oO0K3BBK
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - MINIO_ID=db21_access_key
      - MINIO_PASSWORD=db21_secret_key
      - MINIO_HOST=minio
      - MINIO_PORT=9001
    depends_on:
      - db
    restart: always

volumes:
  minio:
